config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root :to => 'welcome#index'
  get '/welcome' => 'welcome#index'
  get '/logged_in' => 'admin#index'
  get '/login' => 'sessions#unsigned'
  get '/monthly', to: 'monthly#index'
  get '/archive/', to: 'archive#index'
  get '/archive/:slug', to: 'archive#subindex'
  get '/archive/:slug/:subslug', to: 'archive#subsubindex'
  
  get 'stores/:title', to: 'stores#show'
  get 'stores/', to: 'stores#index'
  delete 'stores/:title', to: 'stores#destroy'
  post 'stores/:title', to: 'stores#create'
  put 'categories/set_random_color', to: 'categories#set_random_color'
  

  resources :items, only: [:index, :edit, :new, :create, :update, :destroy]
  resources :users, only: [:new, :create, :update]
  resources :sessions, only: [:create, :destroy]
  resource :user_profile, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :logged_out_user, only: [:index]
  
  def index
  end
end

app/views/welcome/index.html.slim
div class='navbar navbar-expand-lg px-md-4 mb-3' style='background-color: #f5f5f5;'
  div class='container-fluid'
    div class='navbar-brand' style='font-weight: bold; display: inline-grid;'
      = link_to 'HHAB', root_path, class: 'text-decoration-none anim-text-flow2'
      span style='font-weight: bold; margin-top: -1rem; font-size: 0.8rem;'
        = 'house hold account book'

div class='welcome-frame'
  div class='text-center d-block w-100' 
    div class='fw-bold' style='font-size: 4rem;' HHAB
    div class='fw-bold pb-3' style='font-size: 1.5rem;' 生活費を見直そう。

    div class='py-4'
      span class='px-3'
        = link_to 'ログイン', login_path, class: 'link-primary text-decoration-none'
        bi.bi-chevron-right.text-primary
      span class='px-3'
        = link_to '新規ユーザー登録', new_user_path, class: 'link-primary text-decoration-none'
        bi.bi-chevron-right.text-primary
  
    div class='px-1 py-4'
      h5 class=' fw-bold mb-4' 月々の消費割合を確認。
      = image_tag 'sample1.jpg', width: '500', height: '270', alt: 'sample1', class: 'welcome_images'
    div class='px-1 py-4'
      h5 class=' fw-bold mb-4' 月々の消費推移を確認。
      = image_tag 'sample2.jpg', width: '500', height: '250', alt: 'sample2', class: 'welcome_images'
    div class='px-1 py-4'
      h5 class=' fw-bold mb-4' 記録を追加した項目を月ごとに確認。
      = image_tag 'sample3.jpg', width: '500', height: '200', alt: 'sample3', class: 'welcome_images'

javascript:
  const menuButtonElement = document.getElementById("menu-button");
  const sideMenuElement = document.getElementById("side-menu");
  const sideMenuButtonElement = document.getElementById("side-menu-button");

  if (!!sideMenuButtonElement) {
    sideMenuButtonElement.addEventListener('click', (e) => {
      sideMenuElement.className = 'd-none'
    })
    menuButtonElement.addEventListener('click', (e) => {
      sideMenuElement.className = 'd-initial'
    })
  }