config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root :to => 'welcome#index'
  get '/welcome' => 'welcome#index'
  get '/logged_in' => 'admin#index'
  get '/login' => 'sessions#unsigned'
  get '/monthly', to: 'monthly#index'
  get '/archive/', to: 'archive#index'
  get '/archive/:slug', to: 'archive#subindex'
  get '/archive/:slug/:subslug', to: 'archive#subsubindex'
  
  get 'stores/:title', to: 'stores#show'
  get 'stores/', to: 'stores#index'
  delete 'stores/:title', to: 'stores#destroy'
  post 'stores/:title', to: 'stores#create'
  put 'categories/set_random_color', to: 'categories#set_random_color'
  

  resources :items, only: [:index, :edit, :new, :create, :update, :destroy]
  resources :users, only: [:new, :create, :update]
  resources :sessions, only: [:create, :destroy]
  resource :user_profile, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :signed_in_user, only: [:show]

  def show
  end
end

app/views/user_profiles/show.html.slim
- if signed_in?
  = render 'sessions/signed'

  div style='padding: 0 1rem 0 1rem; min-height: 80vh;'
    h4 class='fw-bold pb-1' プロフィール
    - if current_user.present?
      = form_with(url: user_path(current_user), method: :put, html: { class: 'd-grid'}) do |f|
        table class='table table-striped'
          tr
            th class='text-center' ID
            td = current_user.id
          tr
            th class='text-center' Email
            td = current_user.email
          tr
            th class='text-center' 氏名
            td
              div class='form-control me-2 w-100'
                = f.text_field :name, value: current_user.name, class: 'form-control', required: true
          tr
            th class='text-center' 備考
            td 
              div class='form-control me-2 w-100'
                = f.text_area :description, value: current_user.description, class: 'form-control'
          / tr
          /   th class='text-center' 公開設定
          /   td 
          /     div class='form-control me-2 w-100'
          /       = f.radio_button :status, 'active', class: 'form-check-input px-1', checked: current_user.status_active?
          /       = f.label '公開する', class: 'form-check-label px-1'
          /       = f.radio_button :status, 'inactive', class: 'form-check-input px-1', checked: current_user.status_inactive?
          /       = f.label '非公開にする', class: 'form-check-label px-1'
        = f.submit '変更', class: 'btn btn-outline-primary', style: "margin-inline-start: auto; width: 30%;"
- else
  div class='navbar navbar-expand-lg navbar-light bg-light p-3 px-md-4 mb-3'
    div class='container-fluid'
      div class='navbar-brand fs-2 fw-bold' 
        = link_to 'ホーム', items_path, class: 'text-decoration-none'