config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root :to => 'welcome#index'
  get '/welcome' => 'welcome#index'
  get '/logged_in' => 'admin#index'
  get '/login' => 'sessions#unsigned'
  get '/monthly', to: 'monthly#index'
  get '/archive/', to: 'archive#index'
  get '/archive/:slug', to: 'archive#subindex'
  get '/archive/:slug/:subslug', to: 'archive#subsubindex'
  
  get 'stores/:title', to: 'stores#show'
  get 'stores/', to: 'stores#index'
  delete 'stores/:title', to: 'stores#destroy'
  post 'stores/:title', to: 'stores#create'
  put 'categories/set_random_color', to: 'categories#set_random_color'
  

  resources :items, only: [:index, :edit, :new, :create, :update, :destroy]
  resources :users, only: [:new, :create, :update]
  resources :sessions, only: [:create, :destroy]
  resource :user_profile, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :items, foreign_key: 'category_path', primary_key: 'path'
  

  with_options presence: true do
    validates :title
    validates :path
    validates :status
    validates :color
  end

  validates :path, uniqueness: {
    scope: :user_id,
  }

  enum status: {
    draft:      0,  # 下書き
    opened:     1,  # 公開済み
    closed:     2,  # 非公開
  }

  scope :published, -> { where( status: :opened ) }
  scope :incomed, -> { where( income: true ) }
  scope :outcomed, -> { where( income: false ) }

  def status_label
    if self.status == 'draft'
      '下書き'
    elsif self.status == 'opened'
      '公開済み'
    elsif self.status == 'closed'
      '非公開'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :signed_in_user, only: [:index, :new, :create, :edit, :update, :destroy]
  protect_from_forgery

  def index
    @subjects = current_user.categories.order(order: "asc")
    @subjects = @subjects.page(current_page).per(current_limit(10))
  end

  def new
  end

  def create
    current_user.categories.create(category_params)
    redirect_to new_category_path, notice: '作成しました'
  end

  def edit
    @subject = Category.find(params[:id])
  end

  def update
    current_user.categories.find(params[:id]).update!(category_params)
    redirect_to categories_path, notice: '更新しました'
  end
  
  def set_random_color
    @categories = current_user.categories.published.order(order: "asc")
    @colors = @categories.map{|a| "##{Random.bytes(3).unpack1('H*')}55" }
    @categories.map.with_index(0) { |a, index| a.update(color: @colors[index])}
    redirect_to categories_path, notice: '更新しました'
    # ["#f8bcba","#f2c642","#98df35","#38e947","#37e4b9","#aacff7","#c8c6f9","#e5bdf9","#f8b9d7"]
  end

  def destroy
    current_user.categories.find(params[:id]).destroy
    redirect_to categories_path, notice: '削除しました'
  end

  private
    def category_params
      params.require(:category).permit(:title, :path, :color, :income, :order, :status)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.slim
- if signed_in?
  = render 'sessions/signed'

  div class='d-flex' style='padding: 0 1rem 1rem 1rem;'
    button class='sp btn btn-outline-primary m-2' onclick="location.href='#{categories_path}'" style='width: max-content;'
      i class='bi bi-arrow-left p-2'
      | 一覧
    button class='sp btn btn-outline-primary m-2' onclick="location.href='#{new_category_path}'" style='width: max-content;'
      i class='bi bi-plus p-2'
      | 新規作成

  div style='padding: 0 1rem 0 1rem; min-height: 80vh;'
    div class='pt-2 pb-4'
      h4 class='fw-bold text-center' カテゴリ編集フォーム
    - if @subject.present?
      div class='form-format1'
        = form_for(:category, url: category_path(params[:id]), method: :put) do |f|
          div class='form-floating mt-4 mb-3'
            = f.text_field :title, value: @subject.title ,class: 'form-control', id: 'category_title'
            = f.label :title, 'タイトル', for: 'category_title'
          div class='form-floating mt-4 mb-3'
            = f.text_field :path, value: @subject.path, class: 'form-control', id: 'category_path', disabled: true
            = f.label :path, 'パス', for: 'category_path'
          div class='form-floating mt-4 mb-3 d-flex'
            = f.text_field :color, value: @subject.color.slice(0..6), maxLength: 9,id: 'category_color', class: 'form-control color_text_field w-75 me-1', required: true
            = f.color_field :color, value: @subject.color.slice(0..6), id: 'category_color', class: 'form-control arrow_icon_color_selector w-25 ms-1', required: true
            = f.label :color, 'カラー', for: 'category_color', class: 'form-label'
          div class='form-floating mt-4 mb-3'
            = f.select :income, options_for_select([{id: 1, name: '消費扱い', value: false},{id: 2, name: '収入扱い', value: true}].map{|c|[c[:name], c[:value], {}]}, selected: !!@subject.income), {}, {class: 'form-control', id: 'category_income', required: true}
            = f.label :income, '収入', for: 'category_income'
          div class='form-floating mt-4 mb-3'
            = f.text_field :order, value: @subject.order, class: 'form-control', id: 'category_order'
            = f.label :order, '順番', for: 'category_order'
          div class='form-floating mt-4 mb-3'
            = f.select :status, options_for_select([{id: 1, name: '下書き', value: 'draft'},{id: 2, name: '公開済み', value: 'opened'},{id: 3, name: '非公開', value: 'closed'},].map{|c|[c[:name], c[:value], {}]}, @subject.status), {}, {class: 'form-control', id: 'category_status'}
            = f.label :status, 'ステータス', for: 'category_status'
          = f.submit "更新する", class: "btn btn-primary"

  javascript:
    const colorpicker = document.querySelector('.arrow_icon_color_selector');
    const color_text_field = document.querySelector('.color_text_field');
    colorpicker.addEventListener('input', function(e) {
      color_text_field.value = e.target.value;
    });

app/views/categories/index.html.slim
- if signed_in?
  = render 'sessions/signed'

  - if @subjects.present?
    div class='px-5 pt-1 pb-1'
      ul class='nav flex-column pb-2'
        button class='sp btn btn-outline-primary' onclick="location.href='#{new_category_path}'" style='width: max-content;'
          i class='bi bi-plus p-2 px-1'
          | 新規作成
      ul class='nav flex-column pb-2'
        = button_to categories_set_random_color_path, method: :put, data: { disable_with: "作成中...", confirm: "公開状態にあるカラー全てに自動で色を割り当てます。\n本当に作成してもいいですか？" }, class: 'btn btn-outline-primary' , style: 'width: max-content;'
          i class='bi bi-palette-fill px-1'
          | カラーをランダムに一括作成
        

    div class='px-5 pt-1 pb-1' style='min-height: 74vh;'
      div class='pt-2 pb-4'
        h4 class='fw-bold text-center' カテゴリ一覧
      div style='overflow-x: scroll;'
        table class='table text-center table-striped'
          thread
            tr
              th scope='col' ID
              th scope='col' タイトル
              th scope='col' パス
              th scope='col' カラー
              th scope='col' 種類
              th scope='col' 順番
              th scope='col' ステータス
              th scope='col' 削除

          tbody
            - @subjects.map.with_index(1) do |subject, index|
              tr
                td = link_to subject.id, edit_category_path(subject.id), class: 'text-decoration-none'
                td = subject.title
                td = subject.path
                td 
                  div class='category-color nav-link-button' style='background-color: #{subject.color}; width: 4rem; height: 1.5rem;'
                    p class='category-color-tooltip tooltip-top-left' #{subject.color}
                td = !!subject.income ? '収入' : '支出'
                td = subject.order
                td = subject.status_label
                td = button_to '削除する', category_path(subject.id), method: :delete, data: { disable_with: "削除中...", confirm: "本当に削除してもいいですか？" }, class: 'btn btn-outline-danger'

        div id='pagination'
          = paginate @subjects

  - else
    div class='pt-4 pb-3 text-center'
      div class='fw-bold' カテゴリーが作成されていません。
      div class='py-4'
        span class='px-3'
          = link_to 'カテゴリーを作成する', new_category_path, class: 'link-primary text-decoration-none'
          bi.bi-chevron-right.text-primary


javascript:
  document.addEventListener('DOMContentLoaded', () => {
      const colors = document.querySelectorAll('.category-color');
      for(var i = 0; i < colors.length; i++){
        colors[i].addEventListener('mouseover', (e) => {
          const target = e.target.getElementsByClassName('category-color-tooltip')[0]
          if (!!target) { target.style.display = 'initial' }
        },false);
        colors[i].addEventListener('mouseleave', (e) => {
          const target = e.target.getElementsByClassName('category-color-tooltip')[0]
          if (!!target) { target.style.display = 'none' }
        },false);
      }
  },false);

app/views/categories/new.html.slim
- if signed_in?
  = render 'sessions/signed'

  div class='sp px-5 pt-1 pb-1'
    ul class='nav flex-column pb-4'
      button class='sp btn btn-outline-primary' onclick="location.href='#{categories_path}'" style='width: max-content;'
        i class='bi bi-arrow-left p-2'
        | 一覧

  div style='padding: 0 1rem 0 1rem; min-height: 80vh;'
    div class='pt-4 pb-3'
      h4 class='fw-bold' style='text-align: center;' カテゴリー作成フォーム
    div class='form-format1'
      = form_for(:category, url: categories_path, method: :post) do |f|
        div class='form-floating mt-4 mb-3'
          = f.text_field :title, class: 'form-control', id: 'category_title', required: true
          = f.label :title, 'タイトル', for: 'category_title'
        div class='form-floating mt-4 mb-3'
          = f.text_field :path, class: 'form-control', id: 'category_path', required: true
          = f.label :path, 'パス', for: 'category_path'
        div class='form-floating mt-4 mb-3 d-flex'
          = f.text_field :color, maxLength: 9,id: 'category_color', class: 'form-control color_text_field w-75 me-1', required: true
          = f.color_field :color, id: 'category_color', class: 'form-control arrow_icon_color_selector w-25 ms-1', required: true
          = f.label :color, 'カラー', for: 'category_color', class: 'form-label'
        div class='form-floating mt-4 mb-3'
          = f.select :income, options_for_select([{id: 1, name: '消費扱い', value: false},{id: 2, name: '収入扱い', value: true}].map{|c|[c[:name], c[:value], {}]}, false), {}, {class: 'form-control', id: 'category_income'}
          = f.label :income, '収入', for: 'category_income'
        div class='form-floating mt-4 mb-3'
          = f.text_field :order, class: 'form-control', id: 'category_order'
          = f.label :order, '順番', for: 'category_order'
        div class='form-floating mt-4 mb-3'
          = f.select :status, options_for_select([{id: 1, name: '下書き', value: 'draft'},{id: 2, name: '公開済み', value: 'opened'},{id: 3, name: '非公開', value: 'closed'},].map{|c|[c[:name], c[:value], {}]}), { include_blank: 'ステータスが選択されていません' }, {class: 'form-control', id: 'category_status', required: true}
          = f.label :status, 'ステータス', for: 'category_status'
        = f.submit "更新する", class: "btn btn-primary"

  javascript:
    const colorpicker = document.querySelector('.arrow_icon_color_selector');
    const color_text_field = document.querySelector('.color_text_field');
    colorpicker.addEventListener('input', function(e) {
      color_text_field.value = e.target.value;
    });