config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/create'
  get 'categories/edit'
  get 'categories/update'
  get 'categories/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  unless Rails.env.production?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root :to => 'welcome#index'
  get '/welcome' => 'welcome#index'
  get '/logged_in' => 'admin#index'
  get '/login' => 'sessions#unsigned'
  get '/monthly', to: 'monthly#index'
  get '/archive/', to: 'archive#index'
  get '/archive/:slug', to: 'archive#subindex'
  get '/archive/:slug/:subslug', to: 'archive#subsubindex'
  
  get 'stores/:title', to: 'stores#show'
  get 'stores/', to: 'stores#index'
  delete 'stores/:title', to: 'stores#destroy'
  post 'stores/:title', to: 'stores#create'
  put 'categories/set_random_color', to: 'categories#set_random_color'
  

  resources :items, only: [:index, :edit, :new, :create, :update, :destroy]
  resources :users, only: [:new, :create, :update]
  resources :sessions, only: [:create, :destroy]
  resource :user_profile, only: [:show]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  before_action :signed_in_user, only: [:index, :subindex, :new, :create]
  helper_method :sort_column, :sort_direction

  def index
    @months = current_user.items.order("purchased_at desc").group_by{|a|"#{a.purchased_at.year}-#{sprintf("%02d", a.purchased_at.month)}"}.map{|a|[a[0], a[1].count]}
    @months = Kaminari.paginate_array(@months).page(current_page).per(current_limit(10))
  end

  def subindex
    @items = current_user.items
    @date = Date.parse("#{params[:slug]}-01")
    @all_month = ["#{@date} 00:00:00.000000000 JST +09:00".."#{@date.end_of_month} 23:59:59 +0900"]
    @list_items = current_user.items.where(purchased_at: @all_month).order("#{sort_column} #{sort_direction}")
    @list_items = Kaminari.paginate_array(@list_items).page(current_page).per(current_limit(10))

    @charts_title = "#{@date.year}年#{@date.month}月"
    @last_month_items = current_user.items.where(purchased_at: @all_month)
    @categories = current_user.categories.published.order(order: 'asc')
    @categories_title_path = @categories.pluck(:title,:path, :color)
    @items = @last_month_items.group(:category_path).sum(:price)

    @categories_sum = @categories_title_path.map{|a| @items[a[1]] == nil ? 0 : @items[a[1]]}
    @categories_title_path_transposed = @categories_title_path.transpose
    gon.labels = @categories_title_path_transposed[0]
    gon.data = @categories_sum
    gon.polar_area_colors = @categories_title_path_transposed[2]

    days = @date.all_month.map{|a|[a.day, 0, 0]}.transpose
    incomed_items_transpose = @last_month_items.where(category_path: @categories.incomed.pluck(:path)).map{|items| [items.purchased_at.day, items.price]}.transpose
    outcomed_items_transpose = @last_month_items.where(category_path: @categories.outcomed.pluck(:path)).map{|items| [items.purchased_at.day, items.price]}.transpose
    if incomed_items_transpose.any?
      incomed_items_transpose[0].each.with_index(0) do |d, index|
        days[1][d-1] = days[1][d-1] + incomed_items_transpose[1][index]
      end
    end
    if outcomed_items_transpose.any?
      outcomed_items_transpose[0].each.with_index(0) do |d, index|
        days[2][d-1] = days[2][d-1] + outcomed_items_transpose[1][index]
      end
    end
    
    gon.bar_labels = days[0]
    gon.incomed_items_dayly_sum = days[1]
    gon.outcomed_items_dayly_sum = days[2]
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'desc'
  end

  def sort_column
    current_user.items.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end
end

app/views/archive/index.html.slim
- if signed_in?
  = render 'sessions/signed'

  - if @months.present?
    div class='d-flex' style='padding: 0 1rem 1rem 1rem;'
      button class='sp btn btn-outline-primary m-2' onclick="location.href='#{new_item_path}'" style='width: max-content;'
        i class='bi bi-plus p-2'
        | 新規作成
    
    div style='padding: 0 1rem 0 1rem; height: 79vh;'
      div class='pt-2 pb-4'
        h4 class='fw-bold text-center' 毎月の記録一覧
      table class='table text-center table-striped'
        thread
          tr
            th scope='col' 年月
            th scope='col' 件数

        tbody
          - @months.map do |month, count|
            tr
              td = link_to "#{month}", "#{archive_path}/#{month}", class: 'text-decoration-none'
              td = count

      div id='pagination'
        = paginate @months
        / div id='pagination-select'
        /   = select_tag :limit, options_for_select([["30件", 30], ["60件", 60], ["90件", 90]], selected: current_limit), { id: 'pagination-limit', class: ''}

  - else
    div class='pt-4 pb-3 text-center'
      div class='fw-bold' 記録が作成されていません。
      div class='py-4'
        span class='px-3 pc'
          = link_to '記録を作成する', new_item_path, class: 'link-primary text-decoration-none'
          bi.bi-chevron-right.text-primary

app/views/archive/subindex.html.slim
- if signed_in?
  = render 'sessions/signed'

  div class='sp d-flex' style='padding: 0 1rem 1rem 1rem;'
    button class='sp btn btn-outline-primary m-2' onclick="location.href='#{archive_path}'" style='width: max-content;'
      i class='bi bi-arrow-left p-2'
      | 一覧

  div style='padding: 0 1rem 1rem 1rem;'
    h4 class='fw-bold pb-1' = @charts_title
    div class='py-2 text-center'
      canvas id='polar_area' style='max-height: 35rem'
    div class='py-2 text-center' style='font-size: 20px;'
      canvas id='bar' height='#{mobile? ? 400 : 300}' style='max-height: 35rem'

  = render '/chart'

  div style='padding: 0 1rem 0 1rem;'
    h4 class='fw-bold pb-1' 記録一覧
    - if @list_items.present?
      div style='overflow-x: scroll;'
        table id='items_table' class='table text-center table-striped'
          thread
            tr
              th scope='col' 編集
              th scope='col' 名称
              th scope='col' カテゴリ
              th scope='col'
                = sort_order "price", "価格"
              th scope='col'
                = sort_order "purchased_at", "購入日"
              th scope='col' 説明
              th scope='col'
                = sort_order "created_at", "作成日"
              th scope='col' 削除

          tbody
            - @list_items.map do |item| 
              tr
                td = link_to item.id, edit_item_path(item), class: 'text-decoration-none'
                td = item&.store_title || ''
                td = item&.category_path || ''
                td = item.price
                td = l(item.purchased_at, format: :format2)
                td = item.description 
                td = l(item.created_at, format: :format3)
                td = link_to '削除', item_path(item), method: :delete, data: { confirm: "本当に削除してもいいですか？" }, class: 'btn btn-outline-danger'
    
      div id='pagination'
        = paginate @list_items

- else
  div 現在、記録は登録されていません